[package]
name = "atac"
description = "Arguably a Terminal API Client"
version = "0.2.0"
edition = "2021"
authors = ["julien-cpsn"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.24", features = ["cookies"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
strum = "0.26.1"
ratatui = "0.26.1"
crossterm = "0.27.0"
tui-big-text = "0.4.1"
tui-textarea = { version = "0.4.0", features = ["ratatui"] }
throbber-widgets-tui = "0.4.0"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
clap = { version = "4.5.0", features = ["derive", "color"] }
lazy_static = "1.4.0"
